### ISSUE TITLE
请问一下博主copy了这个主题，valine评论加载不出来怎么解决啊

### ISSUE THREAD

**Issue by NeroAsmarr** [JalenChuh/blog#5]
开始是直接用的cards，valine评论正常加载，后面copy这个主题文件进去，然后valine评论就加载不出来了。如图：
![截屏2020-07-12下午7 16 14](https://user-images.githubusercontent.com/44702685/87245064-d494e680-c474-11ea-9079-b6c67b696e3e.png)

**Comment by NeroAsmarr** [comment]
添加一下，这是主题配置文件不变的情况下，原版cards主题有valine评论
![截屏2020-07-12下午7 41 56](https://user-images.githubusercontent.com/44702685/87245455-efb52580-c477-11ea-899a-a1c78edffdd9.png)

**Comment by JalenChuh** [comment]
可否提供一个已经部署好的网址？

**Comment by NeroAsmarr** [comment]
> 可否提供一个已经部署好的网址？

https://neroasmar.top/
现在这个没有评论

**Comment by JalenChuh** [comment]
谢谢，已经修复了 https://github.com/JalenChuh/blog/commit/e5d1da6cfb8d0a408595058d9e8181fb2a006f0f
替换下 layout/_partial/scripts.ejs 就行

**Comment by NeroAsmarr** [comment]
ok了，十分感谢了！！

**Comment by JalenChuh** [comment]
顺便，`layout/_meta/leancloud.ejs` 是基于 leancloud 的访问量统计，如果不需要可以删除

需要的话可以修改其中的 `app_id` `app_key` 和 `server_url`（国际版不需要这个），leancloud 那边不需要其他配置，和 valine 共用一个应用就行

但是我没有进行访问量显示，可以自己添加代码

**Comment by NeroAsmarr** [comment]
好的，谢谢😹  突然发现前端还是真有趣，我现在就一个前端小白，太感谢了
